### PR TITLE
Remove search-ui and associated resources

### PR DESCRIPTION
**Pull request by zlayne**
Signed-off-by: Zack Layne <zlayne@redhat.com>

Related issue: https://github.com/open-cluster-management/backlog/issues/17364

### CODE REVIEW

**Comment by jlpadilla** [comment]
/lgtm
Search UI code has been merged with console.

**Comment by zlayne** [comment]
@jlpadilla @KevinFCormier Thanks for the review. Will leave on hold for now until the search-e2e-test has been update to handle the new routes.

**Comment by jlpadilla** [comment]
@zlayne How are the routes changing?  We should support the existing routes for backward compatibility. We could do it with a redirect.

**Comment by zlayne** [comment]
@jlpadilla The routes are getting update to the following to keep consistency with other console repo routing:
```
/search -> /multicloud/search
/resources -> /multicloud/resources
/multicloud/welcome -> /multicloud/home/welcome
```

**Comment by KevinFCormier** [comment]
@jamestalton Thoughts on redirects for the existing search routes? I don't think we'd want to maintain that forever, and we won't be able to once we move to dynamic plugins. So I think adding the redirect is just delaying people from updating any links they may have.

**Comment by zlayne** [comment]
@KevinFCormier I don't think this would be specific to just the search routes if we decide to use redirects, as many routes have now changed with the recent console rework.

**Comment by jlpadilla** [comment]
Since we are changing routes, do you want to keep the base route as `/multicloud`? The "multicloud" term is now outdated.

However, as a user, I don't like when these things change. 😄

**Pull request merged**
